* Spiderweb
  Wiki software built on the idea of creating many interconnecting links between
  ideas, much like a spiderweb
* Why
  When fantastic tools like Emacs' org-mode already exist for keeping notes, why
  create a new one? There are three primary ways that the spiderweb differs from
  org-mode
** Inter-connectivity
   - The spiderweb wiki is designed to function more like a wiki, so that information
     can easily be accessed by users other than the writer
   - This is especially useful if you wanted to run a pen-and-paper RPG for your
     friends and have an easy way to share and collaborate information with your
     players
** Hierarchy
   - From "CLOSOS Specification of a Lisp operating system" by Robert Strandh : "most
     things are not naturally hierarchical. A hierarchical organization imposes an
     artificial order between names. Whether a document is called
     ~Lisp/Programs/2013/stuff~, ~Programs/Lisp/2013/stuff~, or something else like
     ~2013/Programs/Lisp/Stuff~, is usually not important."
   - Using org-mode headings to organize information, as most people are wont to do
     when writing in org-mode, a hierarchical structure is enforced when it likely
     isn't the best fit for your information
** Relations
   - Org-mode does not necessarily make it easy to find information that is related
     to what you are currently looking at
   - If it's placed under the same heading, sure, it's easy to find. But what if it's
     somewhere else?
* Justification
** Web Technology
   - If you're anything like me, having lived your whole life with atrocious rural
     "internet," then the proliferation of "web apps" over native software is likely
     to be distasteful
   - However, for this use case, I believe the benefits (easy cross-platform
     operation, the ability to work on a project away from home or on your phone
     without needing to carry around multiple copies of an org document and keep
     them in sync, the ability to run the software "in the cloud," etc.) outweigh
     the drawbacks
** Lisp
   - Why is this application written in Common Lisp, a language that no one has cared
     about for 25 years?
   - Because it's the language that I prefer, I'm the one who wrote this software,
     and I wrote it primarily for my own use; if others can find it useful, then
     please use it! But mass adoption isn't really the goal
* Setup
  - Make a file ~conf.lisp~ in the main directory with the rest of the source
  - Start ~conf.lisp~ with the following contents
#+begin_src lisp
(in-package :web)
#+end_src
** Storage
*** Local Files
    - If you can store the files locally (on the same machine the server is running
      from), the setup is easy: add the following lines to ~conf.lisp~
  #+begin_src lisp
  (defparameter *storage-type* :local)
  (defparameter *base-path* "<path to the folder where the data will be stored>/")
  #+end_src
*** S3
    - Not implemented yet
** Proxy
   - Spiderweb wiki is designed to be run behind a reverse-proxy, like nginx
   - The following is a sample nginx configuration
  #+begin_src conf
  http {
       upstream hunchentoot {
         server 127.0.0.1:5000;
       }

       server {
         listen 80;
         listen [::]:80;
         server_name wiki.example.com;

	 location / {
	          proxy_pass http://hunchentoot;
         }
       }
  }
  #+end_src
